# Generated by Django 4.2.7 on 2023-11-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date_create',
        ),
    ]
