# Generated by Django 4.2.7 on 2023-11-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_remove_expense_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sharerequest',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sharerequest',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='spent',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='spent',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
