# Generated by Django 4.2.7 on 2023-11-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spent',
            name='description',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='spent',
            name='date',
            field=models.DateField(),
        ),
    ]
