# Generated by Django 4.2.7 on 2023-11-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_spent_description_alter_spent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spent',
            name='type',
        ),
    ]
