# Generated by Django 4.2.7 on 2023-11-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_remove_spent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spent',
            name='description',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
